"""
Mission Definition Pipeline — data models (the central contract).

These are plain, serializable dataclasses. They carry operator-authored,
design-time intent only. No planning, optimization, or decision logic lives
here — that remains in core/ (the Planning Core).

Two artifacts:
    MissionDefinition : editable, persisted, owned by Mission Planning.
    MissionPackage    : generated by the Planning Core from a definition;
                        execution-ready input for the Digital Twin.

Sub-phases 10D.3-10D.7 enrich MissionDefinition (zones, obstacles, products,
scheduling metadata, ...) without changing this contract's shape.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from typing import Optional

from backend.serializers import JSONObject, JSONValue

# ---------------------------------------------------------------------------
# Mission Definition (design-time input)
# ---------------------------------------------------------------------------


@dataclass
class Zone:
    """An operator-drawn area (crop/management/exclusion). Enriched in 10D.3-4."""

    zone_id: str
    kind: str  # "crop" | "management" | "exclusion" | "treatment"
    label: str
    boundary_points: list[tuple[float, float]]  # local metric (x, y) meters
    crop_type: Optional[str] = None
    enabled: bool = True


@dataclass
class Obstacle:
    """An operator-drawn obstacle/infrastructure marker. Enriched in 10D.3."""

    obstacle_id: str
    kind: str  # "tree" | "pole" | "building" | "irrigation" | "road" | "restricted"
    label: str
    points: list[tuple[float, float]]  # local metric (x, y) meters


@dataclass
class FieldImage:
    """A reference to an uploaded field image (satellite/drone/manual)."""

    image_id: str
    filename: str
    source: str  # "satellite" | "drone" | "manual"
    url: str
    width_px: int = 0
    height_px: int = 0
    uploaded_ms: int = 0


@dataclass
class FieldSpec:
    """
    Field information + preparation data (Phase 10D.3).

    boundary_points, zones and obstacles are user-drawn local metric vertices
    (meters); when boundary is absent, the Planning Core falls back to a
    synthetic rectangle from area_ha (v0.1 compat).

    meters_per_pixel relates the annotation image to metric space so operator
    drawings on the uploaded image become metric geometry the Planning Core
    consumes. Annotation happens in the UI only — no planning is performed here.
    """

    name: str
    crop_type: str
    boundary_points: list[tuple[float, float]] = field(default_factory=list)
    area_ha: Optional[float] = None
    zones: list[Zone] = field(default_factory=list)
    obstacles: list[Obstacle] = field(default_factory=list)
    images: list[FieldImage] = field(default_factory=list)
    meters_per_pixel: float = 0.5
    location: str = ""
    notes: str = ""


@dataclass
class EnvironmentParams:
    """Environmental information consumed by the Planning Core."""

    temperature_c: float = 25.0
    wind_speed_kmh: float = 10.0


@dataclass
class OperationParams:
    """
    Operator planning preferences (intent only — never a computed plan).

    The Mission Designer (10D.4) captures additional preferences (speed,
    overlap, safety margin, coverage direction, route preference). These are
    hints only: the Planning Core decides how to use them. They are optional so
    earlier (10D.2/10D.3) payloads deserialize unchanged.
    """

    operation_type: str = "spray"
    num_drones: int = 3
    flight_altitude_m: Optional[float] = None
    planning_mode: str = "automatic"  # "manual" | "assisted" | "automatic"
    nominal_speed_ms: Optional[float] = None
    overlap_pct: Optional[float] = None
    safety_margin_m: Optional[float] = None
    coverage_direction: str = "auto"  # "auto" | "north_south" | "east_west"
    route_preference: str = "balanced"  # "balanced" | "time" | "battery"


@dataclass
class ProductSelection:
    """
    A chemical/product association (available assets, not allocation).

    The Mission Designer (10D.4) captures application details (tank,
    concentration, dilution, safety notes). These are optional so earlier
    payloads deserialize unchanged. No consumption/allocation is computed here.
    """

    product_id: str
    name: str
    rate_l_per_ha: Optional[float] = None
    tank: Optional[str] = None
    concentration_pct: Optional[float] = None
    dilution: Optional[str] = None
    safety_notes: str = ""


@dataclass
class FleetItem:
    """A selected available drone/asset (selection, not task assignment)."""

    drone_id: int
    model: str
    vendor: str
    battery_capacity_mah: float
    liquid_capacity_l: float
    working_width_m: Optional[float] = None


@dataclass
class MissionDefinition:
    """The central, editable contract every planning screen writes to."""

    name: str
    field: FieldSpec
    operation: OperationParams = field(default_factory=OperationParams)
    environment: EnvironmentParams = field(default_factory=EnvironmentParams)
    fleet: list[FleetItem] = field(default_factory=list)
    products: list[ProductSelection] = field(default_factory=list)
    description: str = ""
    # Mission information captured by the Mission Designer (10D.4). Design-time
    # metadata only — no scheduling/priority logic is performed on these.
    field_id: str = ""
    priority: str = "normal"  # "low" | "normal" | "high" | "urgent"
    scheduled_date: str = ""  # operator estimate (ISO date), not a schedule
    notes: str = ""
    id: str = field(default_factory=lambda: f"mission_{uuid.uuid4().hex[:12]}")
    version: int = 1
    created_ms: int = field(default_factory=lambda: int(time.time() * 1000))
    updated_ms: int = field(default_factory=lambda: int(time.time() * 1000))

    # -- (de)serialization ---------------------------------------------------

    def to_json(self) -> JSONObject:
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "version": self.version,
            "created_ms": self.created_ms,
            "updated_ms": self.updated_ms,
            "field": _field_to_json(self.field),
            "field_id": self.field_id,
            "priority": self.priority,
            "scheduled_date": self.scheduled_date,
            "notes": self.notes,
            "operation": {
                "operation_type": self.operation.operation_type,
                "num_drones": self.operation.num_drones,
                "flight_altitude_m": self.operation.flight_altitude_m,
                "planning_mode": self.operation.planning_mode,
                "nominal_speed_ms": self.operation.nominal_speed_ms,
                "overlap_pct": self.operation.overlap_pct,
                "safety_margin_m": self.operation.safety_margin_m,
                "coverage_direction": self.operation.coverage_direction,
                "route_preference": self.operation.route_preference,
            },
            "environment": {
                "temperature_c": self.environment.temperature_c,
                "wind_speed_kmh": self.environment.wind_speed_kmh,
            },
            "fleet": [
                {
                    "drone_id": item.drone_id,
                    "model": item.model,
                    "vendor": item.vendor,
                    "battery_capacity_mah": item.battery_capacity_mah,
                    "liquid_capacity_l": item.liquid_capacity_l,
                    "working_width_m": item.working_width_m,
                }
                for item in self.fleet
            ],
            "products": [
                {
                    "product_id": p.product_id,
                    "name": p.name,
                    "rate_l_per_ha": p.rate_l_per_ha,
                    "tank": p.tank,
                    "concentration_pct": p.concentration_pct,
                    "dilution": p.dilution,
                    "safety_notes": p.safety_notes,
                }
                for p in self.products
            ],
        }

    @classmethod
    def from_json(cls, data: JSONObject) -> "MissionDefinition":
        field_data = _require_object(data.get("field"), "field")
        op_data = _as_object(data.get("operation"))
        env_data = _as_object(data.get("environment"))

        definition = cls(
            name=_require_str(data.get("name"), "name"),
            field=_field_from_json(field_data),
            operation=OperationParams(
                operation_type=_as_str(op_data.get("operation_type"), "spray"),
                num_drones=_as_int(op_data.get("num_drones"), 3),
                flight_altitude_m=_as_opt_float(op_data.get("flight_altitude_m")),
                planning_mode=_as_str(op_data.get("planning_mode"), "automatic"),
                nominal_speed_ms=_as_opt_float(op_data.get("nominal_speed_ms")),
                overlap_pct=_as_opt_float(op_data.get("overlap_pct")),
                safety_margin_m=_as_opt_float(op_data.get("safety_margin_m")),
                coverage_direction=_as_str(
                    op_data.get("coverage_direction"), "auto"
                ),
                route_preference=_as_str(
                    op_data.get("route_preference"), "balanced"
                ),
            ),
            environment=EnvironmentParams(
                temperature_c=_as_float(env_data.get("temperature_c"), 25.0),
                wind_speed_kmh=_as_float(env_data.get("wind_speed_kmh"), 10.0),
            ),
            fleet=[_fleet_item_from_json(i) for i in _as_list(data.get("fleet"))],
            products=[
                _product_from_json(p) for p in _as_list(data.get("products"))
            ],
            description=_as_str(data.get("description"), ""),
            field_id=_as_str(data.get("field_id"), ""),
            priority=_as_str(data.get("priority"), "normal"),
            scheduled_date=_as_str(data.get("scheduled_date"), ""),
            notes=_as_str(data.get("notes"), ""),
        )
        # Preserve identity/versioning when reloading a persisted record.
        if isinstance(data.get("id"), str):
            definition.id = str(data["id"])
        if isinstance(data.get("version"), int):
            definition.version = int(data["version"])
        if isinstance(data.get("created_ms"), int):
            definition.created_ms = int(data["created_ms"])
        if isinstance(data.get("updated_ms"), int):
            definition.updated_ms = int(data["updated_ms"])
        return definition


# ---------------------------------------------------------------------------
# Field Definition (standalone, persisted — Phase 10D.3)
# ---------------------------------------------------------------------------


@dataclass
class FieldDefinition:
    """
    A persisted, reusable field: its FieldSpec plus identity and timestamps.

    Created and edited in the Field Acquisition & Preparation workflow, then
    referenced by a MissionDefinition. Design-time data only — never runtime.
    """

    spec: FieldSpec
    id: str = field(default_factory=lambda: f"field_{uuid.uuid4().hex[:12]}")
    version: int = 1
    created_ms: int = field(default_factory=lambda: int(time.time() * 1000))
    updated_ms: int = field(default_factory=lambda: int(time.time() * 1000))

    def to_json(self) -> JSONObject:
        payload = _field_to_json(self.spec)
        payload.update(
            {
                "id": self.id,
                "version": self.version,
                "created_ms": self.created_ms,
                "updated_ms": self.updated_ms,
            }
        )
        return payload

    @classmethod
    def from_json(cls, data: JSONObject) -> "FieldDefinition":
        definition = cls(spec=_field_from_json(data))
        if isinstance(data.get("id"), str) and str(data["id"]).strip():
            definition.id = str(data["id"])
        if isinstance(data.get("version"), int):
            definition.version = int(data["version"])
        if isinstance(data.get("created_ms"), int):
            definition.created_ms = int(data["created_ms"])
        if isinstance(data.get("updated_ms"), int):
            definition.updated_ms = int(data["updated_ms"])
        return definition


# ---------------------------------------------------------------------------
# Mission Package (Planning-Core output — execution-ready)
# ---------------------------------------------------------------------------


@dataclass
class MissionPackage:
    """
    The execution-ready artifact produced from a MissionDefinition by the
    Planning Core. Consumed by the Digital Twin; never edited by the UI.

    Fields are plain JSON objects assembled by serializers.build_mission_package
    so this dataclass stays a thin, transport-friendly container.
    """

    definition_id: str
    generated_ms: int
    field_geometry: JSONObject
    routes: list[JSONObject]
    resources: JSONObject
    timeline: JSONObject
    risks: JSONObject
    recommendation: JSONObject
    environment_assessment: JSONObject
    validation: JSONObject
    execution: JSONObject

    def to_json(self) -> JSONObject:
        return {
            "definition_id": self.definition_id,
            "generated_ms": self.generated_ms,
            "field_geometry": self.field_geometry,
            "routes": list(self.routes),
            "resources": self.resources,
            "timeline": self.timeline,
            "risks": self.risks,
            "recommendation": self.recommendation,
            "environment_assessment": self.environment_assessment,
            "validation": self.validation,
            "execution": self.execution,
        }


# ---------------------------------------------------------------------------
# Field / nested (de)serialization helpers
# ---------------------------------------------------------------------------


def _field_to_json(spec: FieldSpec) -> JSONObject:
    return {
        "name": spec.name,
        "crop_type": spec.crop_type,
        "area_ha": spec.area_ha,
        "meters_per_pixel": spec.meters_per_pixel,
        "location": spec.location,
        "notes": spec.notes,
        "boundary_points": [[x, y] for (x, y) in spec.boundary_points],
        "images": [
            {
                "image_id": img.image_id,
                "filename": img.filename,
                "source": img.source,
                "url": img.url,
                "width_px": img.width_px,
                "height_px": img.height_px,
                "uploaded_ms": img.uploaded_ms,
            }
            for img in spec.images
        ],
        "zones": [
            {
                "zone_id": z.zone_id,
                "kind": z.kind,
                "label": z.label,
                "crop_type": z.crop_type,
                "enabled": z.enabled,
                "boundary_points": [[x, y] for (x, y) in z.boundary_points],
            }
            for z in spec.zones
        ],
        "obstacles": [
            {
                "obstacle_id": o.obstacle_id,
                "kind": o.kind,
                "label": o.label,
                "points": [[x, y] for (x, y) in o.points],
            }
            for o in spec.obstacles
        ],
    }


def _field_from_json(data: JSONObject) -> FieldSpec:
    return FieldSpec(
        name=_require_str(data.get("name"), "field.name"),
        crop_type=_as_str(data.get("crop_type"), "generic"),
        area_ha=_as_opt_float(data.get("area_ha")),
        meters_per_pixel=_as_float(data.get("meters_per_pixel"), 0.5),
        location=_as_str(data.get("location"), ""),
        notes=_as_str(data.get("notes"), ""),
        boundary_points=_points_from_json(data.get("boundary_points")),
        images=[_image_from_json(i) for i in _as_list(data.get("images"))],
        zones=[_zone_from_json(z) for z in _as_list(data.get("zones"))],
        obstacles=[_obstacle_from_json(o) for o in _as_list(data.get("obstacles"))],
    )


def _image_from_json(data: JSONObject) -> FieldImage:
    return FieldImage(
        image_id=_as_str(data.get("image_id"), f"img_{uuid.uuid4().hex[:8]}"),
        filename=_as_str(data.get("filename"), ""),
        source=_as_str(data.get("source"), "manual"),
        url=_as_str(data.get("url"), ""),
        width_px=_as_int(data.get("width_px"), 0),
        height_px=_as_int(data.get("height_px"), 0),
        uploaded_ms=_as_int(data.get("uploaded_ms"), 0),
    )


def _zone_from_json(data: JSONObject) -> Zone:
    return Zone(
        zone_id=_as_str(data.get("zone_id"), f"zone_{uuid.uuid4().hex[:8]}"),
        kind=_as_str(data.get("kind"), "crop"),
        label=_as_str(data.get("label"), ""),
        crop_type=_as_opt_str(data.get("crop_type")),
        enabled=bool(data.get("enabled", True)),
        boundary_points=_points_from_json(data.get("boundary_points")),
    )


def _obstacle_from_json(data: JSONObject) -> Obstacle:
    return Obstacle(
        obstacle_id=_as_str(data.get("obstacle_id"), f"obs_{uuid.uuid4().hex[:8]}"),
        kind=_as_str(data.get("kind"), "restricted"),
        label=_as_str(data.get("label"), ""),
        points=_points_from_json(data.get("points")),
    )


def _fleet_item_from_json(data: JSONObject) -> FleetItem:
    return FleetItem(
        drone_id=_as_int(data.get("drone_id"), 0),
        model=_as_str(data.get("model"), "ORION-Std"),
        vendor=_as_str(data.get("vendor"), "ORION"),
        battery_capacity_mah=_as_float(data.get("battery_capacity_mah"), 16000.0),
        liquid_capacity_l=_as_float(data.get("liquid_capacity_l"), 10.0),
        working_width_m=_as_opt_float(data.get("working_width_m")),
    )


def _product_from_json(data: JSONObject) -> ProductSelection:
    return ProductSelection(
        product_id=_as_str(data.get("product_id"), f"prod_{uuid.uuid4().hex[:8]}"),
        name=_as_str(data.get("name"), ""),
        rate_l_per_ha=_as_opt_float(data.get("rate_l_per_ha")),
        tank=_as_opt_str(data.get("tank")),
        concentration_pct=_as_opt_float(data.get("concentration_pct")),
        dilution=_as_opt_str(data.get("dilution")),
        safety_notes=_as_str(data.get("safety_notes"), ""),
    )


# ---------------------------------------------------------------------------
# Typed coercion helpers (avoid Any / getattr)
# ---------------------------------------------------------------------------


class DefinitionValidationError(ValueError):
    """Raised when an incoming Mission Definition payload is malformed."""


def _as_object(value: JSONValue) -> JSONObject:
    return value if isinstance(value, dict) else {}


def _require_object(value: JSONValue, name: str) -> JSONObject:
    if not isinstance(value, dict):
        raise DefinitionValidationError(f"'{name}' must be an object")
    return value


def _as_list(value: JSONValue) -> list[JSONObject]:
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, dict)]


def _points_from_json(value: JSONValue) -> list[tuple[float, float]]:
    if not isinstance(value, list):
        return []
    points: list[tuple[float, float]] = []
    for item in value:
        if isinstance(item, list) and len(item) >= 2:
            x, y = item[0], item[1]
            if isinstance(x, (int, float)) and isinstance(y, (int, float)):
                points.append((float(x), float(y)))
    return points


def _require_str(value: JSONValue, name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise DefinitionValidationError(f"'{name}' is required and must be a string")
    return value


def _as_str(value: JSONValue, default: str) -> str:
    return value if isinstance(value, str) else default


def _as_opt_str(value: JSONValue) -> Optional[str]:
    return value if isinstance(value, str) else None


def _as_int(value: JSONValue, default: int) -> int:
    if isinstance(value, bool):
        return default
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    return default


def _as_float(value: JSONValue, default: float) -> float:
    if isinstance(value, bool):
        return default
    if isinstance(value, (int, float)):
        return float(value)
    return default


def _as_opt_float(value: JSONValue) -> Optional[float]:
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        return float(value)
    return None
